# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global.xci
# IP: The module: 'clk_global' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_global'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_global'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_global'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global.xci
# IP: The module: 'clk_global' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_global'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_global'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/lesson/course_zero/lesson8/ip/clk_global/clk_global_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_global'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
