# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 7
set_param simulator.modelsimInstallPath E:/Modelsim/win64
set_param xicom.use_bs_reader 1
create_project -in_memory -part xcku040-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/Administrator/Desktop/lesson33.2/prj/prj.cache/wt [current_project]
set_property parent.project_path D:/Users/Administrator/Desktop/lesson33.2/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Users/Administrator/Desktop/lesson33.2/prj/prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Users/Administrator/Desktop/lesson33.2/src/uart/uart_rx.v
  D:/Users/Administrator/Desktop/lesson33.2/src/uart/uart_rx_buf.v
  D:/Users/Administrator/Desktop/lesson33.2/src/uart/uart_tx.v
  D:/Users/Administrator/Desktop/lesson33.2/src/uart/uart_tx_buf.v
  D:/Users/Administrator/Desktop/lesson33.2/src/top.v
}
read_ip -quiet D:/Users/Administrator/Desktop/lesson33.2/ip/clk_global/clk_global.xci
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/clk_global/clk_global_board.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/clk_global/clk_global.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/clk_global/clk_global_ooc.xdc]

read_ip -quiet D:/Users/Administrator/Desktop/lesson33.2/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_rx_buf/fifo_uart_rx_buf.xci
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_rx_buf/fifo_uart_rx_buf.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_rx_buf/fifo_uart_rx_buf_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_rx_buf/fifo_uart_rx_buf_ooc.xdc]

read_ip -quiet D:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf.xci
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/Administrator/Desktop/lesson33.2/xdc/xdc.xdc
set_property used_in_implementation false [get_files D:/Users/Administrator/Desktop/lesson33.2/xdc/xdc.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xcku040-ffva1156-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
