######################################################################
#
# File name : test_tb_compile.do
# Created on: Fri Oct 31 15:51:53 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim\\win64\\vlib modelsim_lib/work
E:\\Modelsim\\win64\\vlib modelsim_lib/msim

E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../src/test.v" \
"../../../../../sim/test_tb.v" \


# compile glbl module
E:\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

