######################################################################
#
# File name : test_tb_simulate.do
# Created on: Fri Oct 31 15:51:55 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.test_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {test_tb_wave.do}

view wave
view structure
view signals

do {test_tb.udo}

run 1000ns
