######################################################################
#
# File name : test_tb_wave.do
# Created on: Thu Oct 30 17:00:47 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
