# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/xdc/xdc.xdc

# IP: D:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/ram_next/ram_next.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_next || ORIG_REF_NAME==ram_next} -quiet] -quiet

# IP: D:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/sg_ram/sg_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sg_ram || ORIG_REF_NAME==sg_ram} -quiet] -quiet

# IP: D:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/clk_global/clk_global.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_global || ORIG_REF_NAME==clk_global} -quiet] -quiet

# XDC: d:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/ram_next/ram_next_ooc.xdc

# XDC: d:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/sg_ram/sg_ram_ooc.xdc

# XDC: d:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/clk_global/clk_global_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_global || ORIG_REF_NAME==clk_global} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/clk_global/clk_global.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_global || ORIG_REF_NAME==clk_global} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Users/Administrator/Desktop/FILE/lesson/Num0/lesson16/ip/clk_global/clk_global_ooc.xdc
