######################################################################
#
# File name : tb_compile.do
# Created on: Tue Oct 28 13:28:59 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim\\win64\\vlib modelsim_lib/work
E:\\Modelsim\\win64\\vlib modelsim_lib/msim

E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xpm
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/blk_mem_gen_v8_4_3

E:\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
E:\\Modelsim\\win64\\vmap xpm modelsim_lib/msim/xpm
E:\\Modelsim\\win64\\vmap blk_mem_gen_v8_4_3 modelsim_lib/msim/blk_mem_gen_v8_4_3

E:\\Modelsim\\win64\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../../ip/clk_global" \
"E:/Vivado2019.1/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"E:/Vivado2019.1/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xpm  \
"E:/Vivado2019.1/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \

E:\\Modelsim\\win64\\vlog -64 -incr -work blk_mem_gen_v8_4_3  "+incdir+../../../../../ip/clk_global" \
"../../../../prj.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../ip/clk_global" \
"../../../../../ip/ram_next/sim/ram_next.v" \
"../../../../../ip/sg_ram/sim/sg_ram.v" \
"../../../../../ip/clk_global/clk_global_clk_wiz.v" \
"../../../../../ip/clk_global/clk_global.v" \
"../../../../../src/sg_ram_test.v" \
"../../../../../sim/tb.v" \

# compile glbl module
E:\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

