######################################################################
#
# File name : tb_wave.do
# Created on: Thu May 01 19:14:10 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
