# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf.xci
# IP: The module: 'fifo_uart_tx_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_tx_buf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_tx_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_tx_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf.xci
# IP: The module: 'fifo_uart_tx_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_tx_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_tx_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Users/Administrator/Desktop/lesson33.2/ip/fifo_uart_tx_buf/fifo_uart_tx_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart_tx_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
