######################################################################
#
# File name : multichannel_tb_wave.do
# Created on: Thu Nov 13 15:41:38 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
