######################################################################
#
# File name : multichannel_tb_simulate.do
# Created on: Thu Nov 13 16:28:43 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.multichannel_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {multichannel_tb_wave.do}

view wave
view structure
view signals

do {multichannel_tb.udo}

run 1000ns
