######################################################################
#
# File name : multichannel_tb.udo
# Created on: Thu Nov 13 15:41:38 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
