######################################################################
#
# File name : ram_mem_tb_simulate.do
# Created on: Thu Nov 13 16:07:36 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.ram_mem_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ram_mem_tb_wave.do}

view wave
view structure
view signals

do {ram_mem_tb.udo}

run 1000ns
