######################################################################
#
# File name : ram_mem_tb_compile.do
# Created on: Thu Nov 13 16:07:35 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim\\win64\\vlib modelsim_lib/work
E:\\Modelsim\\win64\\vlib modelsim_lib/msim

E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../ip/ram_chanel/sim/ram_chanel.v" \
"../../../../../src/ram_mem.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -sv -work xil_defaultlib  \
"../../../../../src/adc_data.sv" \

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../../sim/ram_mem_tb.v" \

# compile glbl module
E:\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

