######################################################################
#
# File name : tb_compile.do
# Created on: Thu Oct 24 14:54:21 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../sim/img_gen.v" \
"../../../../../sim/tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

