######################################################################
#
# File name : tb_wave.do
# Created on: Sat Dec 03 21:12:25 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
