######################################################################
#
# File name : tb_compile.do
# Created on: Sun Apr 13 21:39:19 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../ip/clk_global" "+incdir+../../../../../ip/clk_vga" \
"../../../../../ip/clk_vga/clk_vga_clk_wiz.v" \
"../../../../../ip/clk_vga/clk_vga.v" \
"../../../../../ip/clk_global/clk_global_clk_wiz.v" \
"../../../../../ip/clk_global/clk_global.v" \
"../../../../../src/clk_test.v" \
"../../../../../sim/tb.v" \


# compile glbl module
D:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

