######################################################################
#
# File name : tb_wave.do
# Created on: Sun Apr 13 21:28:31 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
