######################################################################
#
# File name : tb_compile.do
# Created on: Fri Nov 21 13:43:10 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim\\win64\\vlib modelsim_lib/work
E:\\Modelsim\\win64\\vlib modelsim_lib/msim

E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../../ip/clk_global" \
"../../../../../ip/fifo_ch0/sim/fifo_ch0.v" \
"../../../../../ip/clk_global/clk_global_clk_wiz.v" \
"../../../../../ip/clk_global/clk_global.v" \
"../../../../../src/pp_fifo.v" \
"../../../../../src/top.v" \
"../../../../../sim/tb.v" \


# compile glbl module
E:\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

