######################################################################
#
# File name : tb_wave.do
# Created on: Thu May 22 10:25:27 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
